CREATE DATABASE $(DB_DATABASE);
GO
USE $(DB_DATABASE);
GO
CREATE LOGIN $(DB_USERNAME) WITH PASSWORD = '$(DB_PASSWORD)';
GO
CREATE USER $(DB_USERNAME) FOR LOGIN $(DB_USERNAME);
GO
ALTER SERVER ROLE sysadmin ADD MEMBER [$(DB_USERNAME)];
GO